# Generated by Django 6.0.5 on 2026-06-14 14:09

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        help_text="Системна назва статусу бронювання (наприклад, 'ACTIVE', 'CANCELLED', 'COMPLETED')",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dormitory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Офіційна назва гуртожитку (наприклад, 'Гуртожиток №3')", max_length=255
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Фізична адреса або геолокація будівлі", max_length=500, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Повна назва факультету (наприклад, Факультет інформатики)",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Назва конкретного ресурсу для бронювання (наприклад, 'Пральна машина №1', 'Душова кабінка №2', 'Піч ліва')",
                        max_length=100,
                    ),
                ),
                (
                    "max_person",
                    models.IntegerField(
                        help_text="Скільки людей можуть одночасно забронювати або використовувати цей ресурс (найчастіше 1)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Якщо True, ресурс недоступний для бронювання (наприклад, зламалася пральна машина)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(help_text="Тип ресурсу, наприклад пралка", max_length=50, unique=True)),
                (
                    "icon_file",
                    models.FileField(
                        help_text="Файл типу ресурсу (у форматі SVG), який буде відмальовуватися на фронтенді",
                        upload_to="resource-icons/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Унікальна назва системної ролі (ADMIN, MODERATOR, RESIDENT)",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        help_text="Категорія приміщення (наприклад, 'Житлова', 'Кухня', 'Душова', 'Пральня')",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialSharingStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        help_text="Системна назва статусу (наприклад, 'ACTIVE', 'CANCELLED', 'COMPLETED')",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TargetType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        help_text="Тип аудиторії, для якої призначене оголошення (наприклад, 'GLOBAL', 'FLOOR', 'ROOM', 'SPECIFIC_USERS')",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "number",
                    models.IntegerField(
                        help_text="Номер поверху (наприклад, 1, 2, 3)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "map_file",
                    models.FileField(
                        help_text="Файл інтерактивної карти поверху (у форматі SVG), на якому відмальовуються кімнати",
                        upload_to="maps/",
                    ),
                ),
                (
                    "notice",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Коротке попередження для відображення на мапі цього поверху, якщо воно потрібне",
                    ),
                ),
                (
                    "dormitory",
                    models.ForeignKey(
                        help_text="Гуртожиток, до якого належить цей поверх",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="api.dormitory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Тільки назва спеціальності (наприклад, Інженерія програмного забезпечення)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        help_text="Факультет, до якого належить ця спеціальність",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="majors",
                        to="api.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Унікальний ідентифікатор користувача (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Корпоративна електронна пошта (наприклад, @ukma.edu.ua)", max_length=254, unique=True
                    ),
                ),
                ("full_name", models.CharField(blank=True, help_text="Повне ім'я мешканця", max_length=500, null=True)),
                (
                    "position",
                    models.CharField(
                        choices=[("STUDENT", "Студент"), ("TEACHER", "Викладач"), ("EMPLOYEE", "Працівник")],
                        default="STUDENT",
                        help_text="Позиція у ВНЗ (Студент, Викладач, Працівник)",
                        max_length=20,
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[("BACHELOR", "Бакалавр"), ("MASTER", "Магістр"), ("PHD", "Аспірант")],
                        help_text="Рівень навчання користувача: бакалаврат, магістратура або аспірантура",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "year",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Курс або рік навчання (від 1 до 4; для магістратури доступні 1-2)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Короткий статус або настрій (відображається в публічному профілі)",
                        max_length=100,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Детальна інформація про себе: інтереси, соц мережі, хобі тощо"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, help_text="Файл аватарки профілю", null=True, upload_to="avatars/"),
                ),
                (
                    "is_activated",
                    models.BooleanField(
                        default=False,
                        help_text="Прапорець активації (стає True після першого логіну та заповнення обов'язкових полів профілю)",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        help_text="Факультет, до якого належить викладач",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_users",
                        to="api.faculty",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        blank=True,
                        help_text="Спеціальність, на якій навчається мешканець",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="api.major",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Системна роль, яка визначає рівень доступу до функцій платформи",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(help_text="Час початку використання ресурсу")),
                ("end_time", models.DateTimeField(help_text="Час завершення використання ресурсу")),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Користувач, який скасував бронювання",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Студент, який забронював ресурс",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Поточний стан цього бронювання",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="api.bookingstatus",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        help_text="Конкретний ресурс, що бронюється (наприклад, 'Пральна машина №2')",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="api.resource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="resource",
            name="resource_type",
            field=models.ForeignKey(
                help_text="Тип ресурсу",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resources",
                to="api.resourcetype",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Номер або назва кімнати (наприклад, '314', 'Кухня лівого крила')", max_length=100
                    ),
                ),
                (
                    "max_person",
                    models.SmallIntegerField(
                        help_text="Максимальна місткість. Для житлових — кількість ліжок, для спільних — ліміт людей.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Якщо True, кімната повністю недоступна (наприклад, через капітальний ремонт, санітарний день тощо)",
                    ),
                ),
                (
                    "svg_element_id",
                    models.CharField(
                        help_text="ID елемента (полігону/шляху) всередині SVG-карти поверху. Використовується фронтендом для підсвічування цієї кімнати при наведенні.",
                        max_length=100,
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        help_text="Поверх, на якому знаходиться кімната",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="api.floor",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        help_text="Тип кімнати, який визначає її призначення та правила використання",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="api.roomtype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="resource",
            name="room",
            field=models.ForeignKey(
                help_text="Кімната або приміщення, де фізично розташований цей ресурс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="api.room",
            ),
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(help_text="Фактичний час, коли користувач натиснув 'Я тут'")),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Час автоматичного скасування присутності (щоб уникнути 'вічних' відміток, якщо людина забула вийти)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Мешканець, який зараз перебуває у певній локації",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Кімната або приміщення (наприклад, 'Кухня 3-го поверху'), де відмітився мешканець",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="api.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Кімната в гуртожитку, за якою закріплений студент",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.room",
            ),
        ),
        migrations.CreateModel(
            name="SocialSharingRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Короткий зміст того, що потрібно (наприклад, 'Позичте праску на годину')",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Точний час створення запиту")),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Студент, який створив запит (наприклад, шукає праску або сіль)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Поточний стан запиту (актуальний чи вже закритий)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="api.socialsharingstatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "custom_location",
                    models.CharField(
                        blank=True,
                        help_text="Власна назва локації, якщо це не кімната і не поверх (наприклад, 'Кухня 3-го поверху', 'Подвір'я')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Коротка назва заходу (наприклад, 'Вечір настільних ігор')", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Детальний опис: що буде відбуватись, що варто взяти з собою тощо",
                        null=True,
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="Запланований час початку івенту")),
                ("end_time", models.DateTimeField(help_text="Орієнтовний час завершення івенту")),
                (
                    "max_person",
                    models.IntegerField(
                        help_text="Максимальна кількість учасників. Якщо 0 — кількість не обмежена",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_faculty_only",
                    models.BooleanField(
                        default=False,
                        help_text="Якщо True, івент бачитимуть і зможуть приєднатися лише студенти факультету організатора",
                    ),
                ),
                (
                    "is_major_only",
                    models.BooleanField(
                        default=False,
                        help_text="Якщо True, івент доступний лише для студентів спеціальності організатора",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Точний час створення запиту")),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Організатор івенту",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Поверх, де відбудеться івент (наприклад, у спільному холі)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.floor",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Список мешканців, які підтвердили свою участь",
                        related_name="participating_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кімната, де відбудеться івент (якщо локація прив'язана до конкретної кімнати)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.room",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Поточний статус івенту",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="api.socialsharingstatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Короткий заголовок оголошення", max_length=255)),
                ("message", models.TextField(help_text="Повний текст оголошення")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Час створення оголошення")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Час, коли оголошення перестане бути актуальним і зникне зі стрічки мешканців, якщо null - до першого перегляду",
                        null=True,
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Якщо True, оголошення буде закріплене вгорі стрічки, незалежно від дати створення",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Автор оголошення (зазвичай Адміністратор або Модератор)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Список конкретних студентів, якщо повідомлення призначене особисто для них",
                        related_name="targeted_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_floor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Оберіть поверх, якщо оголошення стосується лише його мешканців (наприклад, 'Ремонт душу на 3-му поверсі')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="api.floor",
                    ),
                ),
                (
                    "target_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Оберіть кімнату, якщо це адресне попередження або повідомлення для конкретної кімнати",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="api.room",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        help_text="Визначає масштаб аудиторії (кому саме буде показано це оголошення)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="api.targettype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementRead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "read_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Точний час, коли користувач відкрив або позначив оголошення як прочитане",
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        help_text="Оголошення, яке було прочитане",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="api.announcement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Користувач, який переглянув це оголошення",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("announcement", "user")},
            },
        ),
        migrations.AddConstraint(
            model_name="floor",
            constraint=models.UniqueConstraint(fields=("dormitory", "number"), name="unique_floor_per_dormitory"),
        ),
        migrations.AddIndex(
            model_name="presence",
            index=models.Index(fields=["expires_at"], name="presence_expires_at_idx"),
        ),
        migrations.AddIndex(
            model_name="presence",
            index=models.Index(fields=["room", "expires_at"], name="presence_room_expires_idx"),
        ),
        migrations.AddConstraint(
            model_name="presence",
            constraint=models.UniqueConstraint(fields=("user",), name="unique_presence_per_user"),
        ),
        migrations.AddConstraint(
            model_name="socialevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("room__isnull", False),
                    ("floor__isnull", False),
                    ("custom_location__isnull", False),
                    _connector="OR",
                ),
                name="event_must_have_location",
            ),
        ),
    ]
