# Generated by Django 6.0.5 on 2026-05-16 16:14
from django.db import migrations


def insert_initial_data(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    TargetType = apps.get_model('api', 'TargetType')
    RoomType = apps.get_model('api', 'RoomType')
    Dormitory = apps.get_model('api', 'Dormitory')
    Floor = apps.get_model('api', 'Floor')
    Room = apps.get_model('api', 'Room')
    Resource = apps.get_model('api', 'Resource')
    User = apps.get_model('api', 'User')
    Faculty = apps.get_model('api', 'Faculty')
    Major = apps.get_model('api', 'Major')
    SocialSharingStatus = apps.get_model('api', 'SocialSharingStatus')
    BookingStatus = apps.get_model('api', 'BookingStatus')


    Role.objects.bulk_create([
        Role(name='RESIDENT'),
        Role(name='MODERATOR'),
        Role(name='ADMIN'),
    ])

    TargetType.objects.bulk_create([
        TargetType(type='GLOBAL'),
        TargetType(type='FLOOR'),
        TargetType(type='ROOM'),
        TargetType(type='SPECIFIC_USERS'),
    ])

    RoomType.objects.bulk_create([
        RoomType(type='LIVING'),
        RoomType(type='COMMON_AREA'),
        RoomType(type='LAUNDRY'),
        RoomType(type='KITCHEN'),
        RoomType(type='BATHROOM'),
        RoomType(type='STORAGE')
    ])

    SocialSharingStatus.objects.bulk_create([
        SocialSharingStatus(status='ACTIVE'),
        SocialSharingStatus(status='CANCELLED'),
        SocialSharingStatus(status='COMPLETED')
    ])

    BookingStatus.objects.bulk_create([
        BookingStatus(status='ACTIVE'),
        BookingStatus(status='CANCELLED'),
        BookingStatus(status='COMPLETED')
    ])

    faculty_humanities = Faculty.objects.create(name="Факультет гуманітарних наук")
    Major.objects.bulk_create([
        Major(faculty=faculty_humanities, name="Історія"),
        Major(faculty=faculty_humanities, name="Філософія"),
        Major(faculty=faculty_humanities, name="Культурологія"),
        Major(faculty=faculty_humanities, name="Мова, література, компаративістика"),
        Major(faculty=faculty_humanities, name="Англійська мова та українська мова"),
        Major(faculty=faculty_humanities, name="Археологія"),
        Major(faculty=faculty_humanities, name="Юдаїка"),
        Major(faculty=faculty_humanities, name="Теорія, історія літератури та компаративістика"),
        Major(faculty=faculty_humanities, name="Теорія, історія української мови та компаративістика"),
        Major(faculty=faculty_humanities, name="Мови (англійська й українська) та комунікація"),
        Major(faculty=faculty_humanities, name="Історія та археологія")
    ])

    faculty_economics = Faculty.objects.create(name="Факультет економічних наук")
    Major.objects.bulk_create([
        Major(faculty=faculty_economics, name="Економіка"),
        Major(faculty=faculty_economics, name="Фінанси, банківська справа та страхування"),
        Major(faculty=faculty_economics, name="Маркетинг"),
        Major(faculty=faculty_economics, name="Менеджмент")
    ])

    faculty_social = Faculty.objects.create(name="Факультет соціальних наук та соціальних технологій")
    Major.objects.bulk_create([
        Major(faculty=faculty_social, name="Політологія"),
        Major(faculty=faculty_social, name="Соціологія"),
        Major(faculty=faculty_social, name="Міжнародні відносини"),
        Major(faculty=faculty_social, name="Журналістика"),
        Major(faculty=faculty_social, name="Зв’язки з громадськістю")
    ])

    faculty_informatics = Faculty.objects.create(name="Факультет Інформатики")
    Major.objects.bulk_create([
        Major(faculty=faculty_informatics, name="Прикладна математика"),
        Major(faculty=faculty_informatics, name="Інженерія програмного забезпечення"),
        Major(faculty=faculty_informatics, name="Комп'ютерні науки"),
        Major(faculty=faculty_informatics, name="Автоматизація, комп’ютерно-інтегровані технології та робототехніка"),
        Major(faculty=faculty_informatics, name="Кібербезпека та захист інформації")
    ])

    faculty_law = Faculty.objects.create(name="Факультет правничих наук")
    Major.objects.bulk_create([
        Major(faculty=faculty_law, name="Право"),
        Major(faculty=faculty_law, name="Суспільне і приватне врядування"),
        Major(faculty=faculty_law, name="Міжнародне право")
    ])

    faculty_natural = Faculty.objects.create(name="Факультет природничих наук")
    Major.objects.bulk_create([
        Major(faculty=faculty_natural, name="Фізика та астрономія"),
        Major(faculty=faculty_natural, name="Хімія"),
        Major(faculty=faculty_natural, name="Біологія"),
        Major(faculty=faculty_natural, name="Екологія"),
        Major(faculty=faculty_natural, name="Лабораторна діагностика біологічних систем"),
        Major(faculty=faculty_natural, name="Екологія та охорона навколишнього середовища"),
        Major(faculty=faculty_natural, name="Фізика")
    ])

    faculty_school_pro = Faculty.objects.create(name="Києво-Могилянська школа професійної та неперервної освіти")
    Major.objects.bulk_create([
        Major(faculty=faculty_school_pro, name="Політика врядування в місті"),
        Major(faculty=faculty_school_pro, name="Управління освітою"),
        Major(faculty=faculty_school_pro, name="Бізнес-дипломатія і GR-політики")
    ])

    faculty_health = Faculty.objects.create(name="Факультет охорони здоров’я, соціальної роботи та психології")
    Major.objects.bulk_create([
        Major(faculty=faculty_health, name="Соціальна робота"),
        Major(faculty=faculty_health, name="Психологія"),
        Major(faculty=faculty_health, name="Громадське здоров’я"),
        Major(faculty=faculty_health, name="Менеджмент в охороні здоров’я"),
    ])

    faculty_kmbs = Faculty.objects.create(name="Києво-Могилянська Бізнес-Школа")
    Major.objects.bulk_create([
        Major(faculty=faculty_kmbs, name="Presidents' MBA"),
        Major(faculty=faculty_kmbs, name="Executive MBA"),
        Major(faculty=faculty_kmbs, name="Business Analytics and Finance")
    ])

    dorm = Dormitory.objects.create(name="Маккейна")

    living_room_type = RoomType.objects.get(type='LIVING')
    kitchen_type = RoomType.objects.get(type='KITCHEN')
    laundry_type = RoomType.objects.get(type='LAUNDRY')
    common_type = RoomType.objects.get(type='COMMON_AREA')
    storage_type = RoomType.objects.get(type='STORAGE')

    floor1 = Floor.objects.create(dormitory=dorm, number=1, map_file="maps/map_1.svg")
    Floor.objects.create(dormitory=dorm, number=2, map_file="maps/map_2.svg")

    Room.objects.bulk_create([
        Room(floor=floor1, room_type=living_room_type, name="Кімната швейцара", max_person=3, svg_element_id="doorman_room"),
        Room(floor=floor1, room_type=living_room_type, name="Адміністрація", max_person=3, svg_element_id="admin_office"),
        Room(floor=floor1, room_type=living_room_type, name="Вахта", max_person=1, svg_element_id="font_desk"),
    ])
    laundry = Room.objects.create(floor=floor1, room_type=laundry_type, name="Пральня", max_person=1, svg_element_id="washing_room")

    Resource.objects.bulk_create([
        Resource(room=laundry, name="Пралка 1", max_person=1),
        Resource(room=laundry, name="Пралка 2", max_person=1)
    ])

    i = 3
    while i <= 9:
        fl = Floor.objects.create(dormitory=dorm, number=i, map_file="maps/map_" + str(i) + ".svg")

        Room.objects.bulk_create([
            Room(floor=fl, room_type=living_room_type, name=str(i) + "1/2", max_person=3, svg_element_id="room_1"),
            Room(floor=fl, room_type=living_room_type, name=str(i) + "1/1", max_person=3, svg_element_id="room_2"),

            Room(floor=fl, room_type=living_room_type, name=str(i) + "2/2", max_person=4, svg_element_id="room_3"),
            Room(floor=fl, room_type=living_room_type, name=str(i) + "2/1", max_person=1, svg_element_id="room_8"),

            Room(floor=fl, room_type=living_room_type, name=str(i) + "3/2", max_person=3, svg_element_id="room_10"),
            Room(floor=fl, room_type=living_room_type, name=str(i) + "3/3", max_person=3, svg_element_id="room_11"),

            Room(floor=fl, room_type=living_room_type, name=str(i) + "4/1", max_person=1, svg_element_id="room_5"),
            Room(floor=fl, room_type=living_room_type, name=str(i) + "4/2", max_person=2, svg_element_id="room_6"),
            Room(floor=fl, room_type=living_room_type, name=str(i) + "4/3", max_person=3, svg_element_id="room_7"),
            Room(floor=fl, room_type=living_room_type, name=str(i) + "4/4", max_person=4, svg_element_id="room_12"),
        ])

        if i == 3:
            Room.objects.create(
                floor=fl,
                room_type=common_type,
                name="Спільний простір " + str(i) + "1/3",
                max_person=10,
                svg_element_id="room_4"
            )
        elif i == 4:
            Room.objects.create(
                floor=fl,
                room_type=storage_type,
                name="Склад " + str(i) + "1/3",
                max_person=0,
                svg_element_id="room_4"
            )
        else:
            Room.objects.create(
                floor=fl,
                room_type=living_room_type,
                name=str(i) + "1/3",
                max_person=1,
                svg_element_id="room_4"
            )

        if i == 5 or i == 9:
            kitchen = Room.objects.create(
                floor=fl,
                room_type=kitchen_type,
                name="Кухня " + str(i) + "3/1",
                max_person=4,
                svg_element_id="room_9"
            )
            Resource.objects.bulk_create([
                Resource(room=kitchen, name="Варильна поверхня 1", max_person=4),
                Resource(room=kitchen, name="Варильна поверхня 2", max_person=4),
                Resource(room=kitchen, name="Духова шафа 1", max_person=1),
                Resource(room=kitchen, name="Духова шафа 2", max_person=1)
            ])
        else:
            Room.objects.create(
                floor=fl,
                room_type=living_room_type,
                name=str(i) + "3/1",
                max_person=1,
                svg_element_id="room_9"
            )

        i += 1


def reverse_initial_data(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    TargetType = apps.get_model('api', 'TargetType')
    RoomType = apps.get_model('api', 'RoomType')
    Dormitory = apps.get_model('api', 'Dormitory')
    Faculty = apps.get_model('api', 'Faculty')
    User = apps.get_model('api', 'User')
    SocialSharingStatus = apps.get_model('api', 'SocialSharingStatus')

    User.objects.all().delete()
    Dormitory.objects.all().delete()
    Faculty.objects.all().delete()
    Role.objects.all().delete()
    TargetType.objects.all().delete()
    RoomType.objects.all().delete()
    SocialSharingStatus.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_initial_data, reverse_initial_data),
    ]
