# Generated by Django 6.0.5 on 2026-05-16 16:14
from django.contrib.auth.hashers import make_password
from django.db import migrations


def insert_initial_data(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    TargetType = apps.get_model('api', 'TargetType')
    RoomType = apps.get_model('api', 'RoomType')
    Dormitory = apps.get_model('api', 'Dormitory')
    Floor = apps.get_model('api', 'Floor')
    Room = apps.get_model('api', 'Room')
    Resource = apps.get_model('api', 'Resource')
    User = apps.get_model('api', 'User')
    Faculty = apps.get_model('api', 'Faculty')
    Major = apps.get_model('api', 'Major')

    #Статичні дані (які будуть завжди)

    Role.objects.bulk_create([
        Role(name='RESIDENT'),
        Role(name='MODERATOR'),
        Role(name='ADMIN'),
    ])

    TargetType.objects.bulk_create([
        TargetType(type='GLOBAL'),
        TargetType(type='FLOOR'),
        TargetType(type='ROOM'),
        TargetType(type='SPECIFIC_USERS'),
    ])

    RoomType.objects.bulk_create([
        RoomType(type='LIVING'),
        RoomType(type='COMMON_AREA'),
        RoomType(type='LAUNDRY'),
        RoomType(type='KITCHEN'),
        RoomType(type='BATHROOM')
    ])

    faculty_humanities = Faculty.objects.create(name="Факультет гуманітарних наук")
    Major.objects.bulk_create([
        Major(faculty=faculty_humanities, name="Історія"),
        Major(faculty=faculty_humanities, name="Філософія"),
        Major(faculty=faculty_humanities, name="Культурологія"),
        Major(faculty=faculty_humanities, name="Мова, література, компаративістика"),
        Major(faculty=faculty_humanities, name="Англійська мова та українська мова"),
        Major(faculty=faculty_humanities, name="Археологія"),
        Major(faculty=faculty_humanities, name="Юдаїка"),
        Major(faculty=faculty_humanities, name="Теорія, історія літератури та компаративістика"),
        Major(faculty=faculty_humanities, name="Теорія, історія української мови та компаративістика"),
        Major(faculty=faculty_humanities, name="Мови (англійська й українська) та комунікація"),
        Major(faculty=faculty_humanities, name="Історія та археологія")
    ])

    faculty_economics = Faculty.objects.create(name="Факультет економічних наук")
    Major.objects.bulk_create([
        Major(faculty=faculty_economics, name="Економіка"),
        Major(faculty=faculty_economics, name="Фінанси, банківська справа та страхування"),
        Major(faculty=faculty_economics, name="Маркетинг"),
        Major(faculty=faculty_economics, name="Менеджмент")
    ])

    faculty_social = Faculty.objects.create(name="Факультет соціальних наук та соціальних технологій")
    Major.objects.bulk_create([
        Major(faculty=faculty_social, name="Політологія"),
        Major(faculty=faculty_social, name="Соціологія"),
        Major(faculty=faculty_social, name="Міжнародні відносини"),
        Major(faculty=faculty_social, name="Журналістика"),
        Major(faculty=faculty_social, name="Зв’язки з громадськістю")
    ])

    faculty_informatics = Faculty.objects.create(name="Факультет Інформатики")
    Major.objects.bulk_create([
        Major(faculty=faculty_informatics, name="Прикладна математика"),
        Major(faculty=faculty_informatics, name="Інженерія програмного забезпечення"),
        Major(faculty=faculty_informatics, name="Комп'ютерні науки"),
        Major(faculty=faculty_informatics, name="Автоматизація, комп’ютерно-інтегровані технології та робототехніка"),
        Major(faculty=faculty_informatics, name="Кібербезпека та захист інформації")
    ])

    faculty_law = Faculty.objects.create(name="Факультет правничих наук")
    Major.objects.bulk_create([
        Major(faculty=faculty_law, name="Право"),
        Major(faculty=faculty_law, name="Суспільне і приватне врядування"),
        Major(faculty=faculty_law, name="Міжнародне право")
    ])

    faculty_natural = Faculty.objects.create(name="Факультет природничих наук")
    Major.objects.bulk_create([
        Major(faculty=faculty_natural, name="Фізика та астрономія"),
        Major(faculty=faculty_natural, name="Хімія"),
        Major(faculty=faculty_natural, name="Біологія"),
        Major(faculty=faculty_natural, name="Екологія"),
        Major(faculty=faculty_natural, name="Лабораторна діагностика біологічних систем"),
        Major(faculty=faculty_natural, name="Екологія та охорона навколишнього середовища"),
        Major(faculty=faculty_natural, name="Фізика")
    ])

    faculty_school_pro = Faculty.objects.create(name="Києво-Могилянська школа професійної та неперервної освіти")
    Major.objects.bulk_create([
        Major(faculty=faculty_school_pro, name="Політика врядування в місті"),
        Major(faculty=faculty_school_pro, name="Управління освітою"),
        Major(faculty=faculty_school_pro, name="Бізнес-дипломатія і GR-політики")
    ])

    faculty_health = Faculty.objects.create(name="Факультет охорони здоров’я, соціальної роботи та психології")
    Major.objects.bulk_create([
        Major(faculty=faculty_health, name="Соціальна робота"),
        Major(faculty=faculty_health, name="Психологія"),
        Major(faculty=faculty_health, name="Громадське здоров’я"),
        Major(faculty=faculty_health, name="Менеджмент в охороні здоров’я"),
    ])

    faculty_kmbs = Faculty.objects.create(name="Києво-Могилянська Бізнес-Школа")
    Major.objects.bulk_create([
        Major(faculty=faculty_kmbs, name="Presidents' MBA"),
        Major(faculty=faculty_kmbs, name="Executive MBA"),
        Major(faculty=faculty_kmbs, name="Business Analytics and Finance")
    ])

    dorm = Dormitory.objects.create(name="Маккейна")

    # Тестові дані

    floor4 = Floor.objects.create(dormitory=dorm, number=4)

    living_room_type = RoomType.objects.get(type='LIVING')
    kitchen_type = RoomType.objects.get(type='KITCHEN')
    laundry_type = RoomType.objects.get(type='LAUNDRY')
    common_type = RoomType.objects.get(type='COMMON_AREA')

    room_41_1 = Room.objects.create(floor=floor4, room_type=living_room_type, name="41/1", max_person=10, svg_element_id="rect-41-1")
    room_admin = Room.objects.create(floor=floor4, room_type=living_room_type, name="Адміністрація-4", max_person=2, svg_element_id="rect-admin")

    kitchen = Room.objects.create(floor=floor4, room_type=kitchen_type, name="Кухня 4-го поверху", max_person=10,
                                  svg_element_id="rect-kitchen-4")
    laundry = Room.objects.create(floor=floor4, room_type=laundry_type, name="Пральня 4-го поверху", max_person=4,
                                  svg_element_id="rect-laundry-4")
    common_area = Room.objects.create(floor=floor4, room_type=common_type, name="Спільний простір", max_person=15,
                                      svg_element_id="rect-common-4")

    Resource.objects.bulk_create([
        Resource(room=kitchen, name="Плита 1", max_person=4),
        Resource(room=laundry, name="Пральна машина 1", max_person=2),
        Resource(room=laundry, name="Сушильна машина 1", max_person=1),
    ])

    faculty_t = Faculty.objects.create(name="Тестовий факультет")
    major_t = Major.objects.create(faculty=faculty_t, name="Тестова спеціальність")

    resident_role = Role.objects.get(name='RESIDENT')
    moderator_role = Role.objects.get(name='MODERATOR')
    admin_role = Role.objects.get(name='ADMIN')

    unusable_password = make_password(None)
    admin_password = make_password("Qwerty1234!")

    User.objects.bulk_create([
        User(email="d.bezukh@ukma.edu.ua", password=unusable_password, role=resident_role, room=room_41_1, is_activated=False),
        User(email="b.zmeul@ukma.edu.ua", password=unusable_password, role=resident_role, room=room_41_1, is_activated=False),
        User(email="d.lapko@ukma.edu.ua", password=unusable_password, role=resident_role, room=room_41_1, is_activated=False),
    ])

    User.objects.bulk_create([
        User(
            email="user1@ukma.edu.ua", password=unusable_password, role=resident_role, room=room_41_1,
            is_activated=True,
            name="Дмитро", surname="Коваленко", year=4, major=major_t, status="Вчуся",
            bio="Працюю над проєктами та дедлайнами."
        ),
        User(
            email="user2@ukma.edu.ua", password=unusable_password, role=resident_role, room=room_41_1,
            is_activated=True,
            name="Іван", surname="Шевченко", year=3, major=major_t,
            bio="Збираю ресурси на лабораторні роботи."
        ),
        User(
            email="user3@ukma.edu.ua", password=unusable_password, role=resident_role, room=room_41_1,
            is_activated=True,
            name="Олексій", surname="Бойко", year=2, major=major_t, status="На кухні",
        ),
    ])

    User.objects.create(
        email="moderator@ukma.edu.ua",
        password=unusable_password,
        role=moderator_role,
        room=room_admin,
        is_activated=True,
        name="Староста",
        surname="Поверху",
    )

    User.objects.create(
        email="admin@ukma.edu.ua",
        password=admin_password,
        role=admin_role,
        room=room_admin,
        is_activated=True,
        is_staff=True,
        is_superuser=True,
        name="Головний",
        surname="Адміністратор",
        status="Бог сервера",
        bio="Маю доступ до всіх таблиць бази даних."
    )

def reverse_initial_data(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    TargetType = apps.get_model('api', 'TargetType')
    RoomType = apps.get_model('api', 'RoomType')
    Dormitory = apps.get_model('api', 'Dormitory')
    Faculty = apps.get_model('api', 'Faculty')
    User = apps.get_model('api', 'User')

    User.objects.all().delete()
    Dormitory.objects.all().delete()
    Faculty.objects.all().delete()
    Role.objects.all().delete()
    TargetType.objects.all().delete()
    RoomType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_initial_data, reverse_initial_data),
    ]
