# Generated by Django 6.0.5 on 2026-05-22
from django.db import migrations

REMAP = {
    "41/1": "room_1",
    "Адміністрація-4": "room_2",
    "Спільний простір": "room_3",
    "Кухня 4-го поверху": "room_4",
    "Пральня 4-го поверху": "room_5",
}

NEW_ROOMS = [
    ("Кімната 41/2", "room_6"),
    ("Кімната 41/3", "room_7"),
    ("Кімната 41/4", "room_8"),
    ("Кімната 41/5", "room_9"),
    ("Кімната 41/6", "room_10"),
    ("Кімната 41/7", "room_11"),
    ("Кімната 41/8", "room_12"),
]


def seed_floor_4(apps, schema_editor):
    Floor = apps.get_model("api", "Floor")
    Room = apps.get_model("api", "Room")
    RoomType = apps.get_model("api", "RoomType")

    floor4 = Floor.objects.filter(number=4).first()
    if floor4 is None:
        return

    for name, svg_id in REMAP.items():
        Room.objects.filter(name=name, floor=floor4).update(svg_element_id=svg_id)

    living = RoomType.objects.get(type="LIVING")
    for name, svg_id in NEW_ROOMS:
        Room.objects.get_or_create(
            floor=floor4,
            svg_element_id=svg_id,
            defaults={"name": name, "room_type": living, "max_person": 4},
        )

    Floor.objects.filter(pk=floor4.pk).update(map_file="maps/floor_4.svg")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_seed"),
    ]

    operations = [
        migrations.RunPython(seed_floor_4, migrations.RunPython.noop),
    ]
