# Generated by Django 6.0.5 on 2026-06-14 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialevent',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Користувач (модератор/адмін), який заблокував/скасував івент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialsharingrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Користувач (модератор/адмін), який заблокував/скасував запит', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sharing_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
