# Generated by Django 6.0.5 on 2026-06-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_education_level_alter_user_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                help_text="Факультет, до якого належить викладач",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_users",
                to="api.faculty",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[("STUDENT", "Студент"), ("TEACHER", "Викладач"), ("EMPLOYEE", "Працівник")],
                default="STUDENT",
                help_text="Позиція у ВНЗ (Студент, Викладач, Працівник)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[("BACHELOR", "Бакалавр"), ("MASTER", "Магістр"), ("PHD", "Аспірант")],
                help_text="Рівень навчання користувача: бакалаврат, магістратура або аспірантура",
                max_length=20,
                null=True,
            ),
        ),
    ]
